# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ruben/Desktop/async_kalman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ruben/Desktop/async_kalman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruben/Desktop/async_kalman/CMakeFiles /home/ruben/Desktop/async_kalman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ruben/Desktop/async_kalman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named async_kalman

# Build rule for target.
async_kalman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 async_kalman
.PHONY : async_kalman

# fast build rule for target.
async_kalman/fast:
	$(MAKE) -f CMakeFiles/async_kalman.dir/build.make CMakeFiles/async_kalman.dir/build
.PHONY : async_kalman/fast

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

#=============================================================================
# Target rules for targets named simulation

# Build rule for target.
simulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simulation
.PHONY : simulation

# fast build rule for target.
simulation/fast:
	$(MAKE) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/build
.PHONY : simulation/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

demo.o: demo.cpp.o
.PHONY : demo.o

# target to build an object file
demo.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.o
.PHONY : demo.cpp.o

demo.i: demo.cpp.i
.PHONY : demo.i

# target to preprocess a source file
demo.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.i
.PHONY : demo.cpp.i

demo.s: demo.cpp.s
.PHONY : demo.s

# target to generate assembly for a file
demo.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/demo.cpp.s
.PHONY : demo.cpp.s

kalman_odometry.o: kalman_odometry.cpp.o
.PHONY : kalman_odometry.o

# target to build an object file
kalman_odometry.cpp.o:
	$(MAKE) -f CMakeFiles/async_kalman.dir/build.make CMakeFiles/async_kalman.dir/kalman_odometry.cpp.o
.PHONY : kalman_odometry.cpp.o

kalman_odometry.i: kalman_odometry.cpp.i
.PHONY : kalman_odometry.i

# target to preprocess a source file
kalman_odometry.cpp.i:
	$(MAKE) -f CMakeFiles/async_kalman.dir/build.make CMakeFiles/async_kalman.dir/kalman_odometry.cpp.i
.PHONY : kalman_odometry.cpp.i

kalman_odometry.s: kalman_odometry.cpp.s
.PHONY : kalman_odometry.s

# target to generate assembly for a file
kalman_odometry.cpp.s:
	$(MAKE) -f CMakeFiles/async_kalman.dir/build.make CMakeFiles/async_kalman.dir/kalman_odometry.cpp.s
.PHONY : kalman_odometry.cpp.s

kalman_operations.o: kalman_operations.cpp.o
.PHONY : kalman_operations.o

# target to build an object file
kalman_operations.cpp.o:
	$(MAKE) -f CMakeFiles/async_kalman.dir/build.make CMakeFiles/async_kalman.dir/kalman_operations.cpp.o
.PHONY : kalman_operations.cpp.o

kalman_operations.i: kalman_operations.cpp.i
.PHONY : kalman_operations.i

# target to preprocess a source file
kalman_operations.cpp.i:
	$(MAKE) -f CMakeFiles/async_kalman.dir/build.make CMakeFiles/async_kalman.dir/kalman_operations.cpp.i
.PHONY : kalman_operations.cpp.i

kalman_operations.s: kalman_operations.cpp.s
.PHONY : kalman_operations.s

# target to generate assembly for a file
kalman_operations.cpp.s:
	$(MAKE) -f CMakeFiles/async_kalman.dir/build.make CMakeFiles/async_kalman.dir/kalman_operations.cpp.s
.PHONY : kalman_operations.cpp.s

simulation.o: simulation.cpp.o
.PHONY : simulation.o

# target to build an object file
simulation.cpp.o:
	$(MAKE) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/simulation.cpp.o
.PHONY : simulation.cpp.o

simulation.i: simulation.cpp.i
.PHONY : simulation.i

# target to preprocess a source file
simulation.cpp.i:
	$(MAKE) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/simulation.cpp.i
.PHONY : simulation.cpp.i

simulation.s: simulation.cpp.s
.PHONY : simulation.s

# target to generate assembly for a file
simulation.cpp.s:
	$(MAKE) -f CMakeFiles/simulation.dir/build.make CMakeFiles/simulation.dir/simulation.cpp.s
.PHONY : simulation.cpp.s

tests.o: tests.cpp.o
.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i
.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s
.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... async_kalman"
	@echo "... demo"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simulation"
	@echo "... tests"
	@echo "... demo.o"
	@echo "... demo.i"
	@echo "... demo.s"
	@echo "... kalman_odometry.o"
	@echo "... kalman_odometry.i"
	@echo "... kalman_odometry.s"
	@echo "... kalman_operations.o"
	@echo "... kalman_operations.i"
	@echo "... kalman_operations.s"
	@echo "... simulation.o"
	@echo "... simulation.i"
	@echo "... simulation.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

